namespace Fs.Obsidian

open Aciq.MyriadPlugins.Attribute

[<CLIMutable>]        
[<Generator.SetFieldByName "settings">]
type PluginSettings =
    {
        defaultCodeBlockLanguage : string
        defaultCalloutType : string
        defaultModalCommand: string
    }
    static member Default = {
        defaultCodeBlockLanguage = "bash"
        defaultCalloutType = "info"
        defaultModalCommand = "obsidian-another-quick-switcher:search-command_Recent search"
    }

//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec Fs.Obsidian.Gen

module PluginSettings =
    open Fs.Obsidian

    let setFieldByName (key: string) (value: _) (x: PluginSettings) =
        match key with
        | "defaultCodeBlockLanguage" -> { x with defaultCodeBlockLanguage = unbox value }
        | "defaultCalloutType" -> { x with defaultCalloutType = unbox value }
        | "defaultModalCommand" -> { x with defaultModalCommand = unbox value }
        | _ -> failwith "unimplemented case"

